#ifndef GRAPH_CONSTRAINT_SNAP_H__
#define GRAPH_CONSTRAINT_SNAP_H__

enum
{
    GRAPH_CONSTRAINT_SNAP_NAME          = 1000,
    GRAPH_CONSTRAINT_SNAP_MAIN_GROUP    = 1001,
    GRAPH_CONSTRAINT_SNAP_X             = 1002,
    GRAPH_CONSTRAINT_SNAP_Y             = 1003,
    GRAPH_CONSTRAINT_SNAP_Z             = 1004,
    GRAPH_CONSTRAINT_SNAP_CREDIT_TXT    = 1005
};

#endif
