CONTAINER GRAPH_CONSTRAINT_SNAP
{
  NAME GRAPH_CONSTRAINT_SNAP_NAME;

  GROUP GRAPH_CONSTRAINT_SNAP_MAIN_GROUP
  {
      GROUP
    {
          COLUMNS 3;
          BOOL GRAPH_CONSTRAINT_SNAP_X { }
          BOOL GRAPH_CONSTRAINT_SNAP_Y { }
          BOOL GRAPH_CONSTRAINT_SNAP_Z { }

    }
    SEPARATOR { LINE; } 
    STATICTEXT  GRAPH_CONSTRAINT_SNAP_CREDIT_TXT {}
  }

	
}
